[package]
name = "javascript-dlc"
version = "0.1.0"
authors = ["AreaLayer <area@arealayer.com>"]
edition = "2018"


[lib]
crate-type = ["cdylib"]
javascript-dlc = "0.1.0"

[dependencies]
wasm-bindgen = "0.2"
