[package]
name = "javascript-dlc"
version = "0.1.9"
authors = ["AreaLayer <arealayer.net>"]
edition = "2018"


[lib]
crate-type = ["cdylib"]
path = "src/lib.rs"

[dependencies]
wasm-bindgen = "0.2.99"
web-sys = { version = "0.3.76", features = ["console"] }
