# Bitcoin Core RPC settings
bitcoin_rpc:
  enabled: true
  host: localhost
  port: 8332
  username: your_bitcoin_rpc_username
  password: your_bitcoin_rpc_password

# Lightning Node settings
lightning_node:
  enabled: true
  implementation: Lightning Node  # Replace with your Lightning implementation (e.g., LND, Eclair, etc.)
  host: localhost
  port: 9735
  pubkey: your_lightning_node_pubkey
  rpc_host: localhost
  rpc_port: 8080  # Replace with the actual RPC port for your Lightning Node
  rpc_username: your_lightning_rpc_username
  rpc_password: your_lightning_rpc_password


# DLC (Discreet Log Contract) settings
dlc:
  contract: deployed_contract_on_chain  # Replace with your DLC contract details
  utxo:  # UTXO details for the DLC
    transaction_id: your_utxo_transaction_id
    vout: your_utxo_vout

# Network settings
network:
  mainnet: true  # Set to true for mainnet, false for testnet

# Other settings
other_settings:
  log_level: info  # Set the desired log level (info, debug, error, etc.)
  data_directory: /path/to/your/data/directory
  network: mainnet  # Change to testnet if you're using the Bitcoin testnet
