openapi: 3.0.3
info:
  title: Javascript DLC
  description: |-
    This is the OpenAPI specification for the
    [Javascript DLC](https://github.com/AreaLayer/Javascript-DLC).
    name: MIT
    url: https://mit-license.org/
  version: 0.1.0
servers:
  - url: http://localhost:3001
  - url: http://localhost:3002
  - url: http://localhost:3003
tags:
  - name: Channels
    description: APIs to perform operations related to LN channels
  - name: Peers
    description: APIs to perform operations related to LN peers
  - name: Payments
    description: APIs to perform operations related to LN payments
  - name: Invoices
    description: APIs to perform operations related to LN invoices
  - name: On-chain
    description: APIs to perform on-chain operations
  - name: RGB
    description: APIs to perform RGB operations
  - name: Other
    description: APIs to perform 
